// http://www.northwestern.edu/brand/visual-identity/color/digital-colors.html
export const northwesternPurple = '#4E2A84'
export const northwesternPurple60 = '#836EAA'
export const northwesternPurple120 = '#401F68'
export const northwesternPurple30 = '#B6ACD1'
export const northwesternPurple10 = '#E4E0EE'
export const richBlack80 = '#342F2E'
export const richBlack50 = '#716C6B'
export const richBlack20 = '#BBB8B8'
export const richBlack10 = '#D8D6D6'
// http://www.northwestern.edu/brand/visual-identity/color/secondary-palette.html
export const brightGreen = '#58B947'
export const brightCyan = '#7FCECD'
export const brightBlue = '#5091CD'
export const brightYellow = '#EDE93B'
export const brightOrange = '#FFC520'
export const brightRed = '#EF553F'
export const darkGreen = '#008656'
export const darkCyan = '#007FA4'
export const darkBlue = '#0D2D6C'
export const darkYellow = '#D9C826'
export const darkOrange = '#CA7C1B'
export const darkRed = '#D85820'
